apiVersion: v1
kind: Config 
clusters:
- name: my-kube-playground
  cluster:
    server: x.x.x.x:6443
    certificate-authority: ca.crt 
contexts:
- name: my-kube-admin@my-kube-playground 
  context:
    cluster: my-kube-playground
    user: my-kube-admin
users:
- name: my-kube-admin
  user:
    client-certificate: admin.crt 
    client-key: admin.key 

