apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: app1 
    tier: FE 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app1
        tier: FE 
    spec:
      containers:
      - name: nginx 
        image: nginx 
  selector:
    matchLabels:
      app: app1 
      