
# developer-role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
- apiGroups: [""]
  resources: ["Pod"]
  verbs: ["list","get","create,"delete","update"]
- apiGroups:[""]
  resources: ["ConfigMap"]
  verbs: ["create"]
  res

---
# role binding for dev 

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
subjects:
- kind: User
  name: dev-user
  apiGroup: rbac.authorization.k8s.io 
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io



# check access

kubectl auth can-i create pods >> yes 

kubectl auth can-i create pods --as dev-user >> checkfordev-user 

