apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller-def
  labels:
    app: myapp
    tier: FE
spec:
  replicas: 3
  template:
    metadata: 
      name: ReplicationController
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx